### ISSUE TITLE
Invalid names

### ISSUE THREAD

**Issue by loga4m** [AbduazizZiyodov/docker-dashboard#2]
![image](https://user-images.githubusercontent.com/74463827/179969085-5de95739-52c4-4817-bd6f-a4f1ccaf0dc9.png)

Look at the image. I've entered an invalid name. App showed a message that this is an invalid name. But after it, App continued showing the Running... message for valid names. 

If user enters invalid name:
     show(InvalidMessage())
     dont_show(RunningMessage())

Or is this behavior is project feature if I've mistaken?

**Comment by AxadjonovOyatillo21** [comment]
![image](https://user-images.githubusercontent.com/74463827/179970097-f357640d-67c0-49b4-af2c-e3aaf6b9c890.png)

 1. Same issue when I've entered the name of the existing container.

![image](https://user-images.githubusercontent.com/74463827/179970546-1615eeca-4a9d-47a5-a716-4a0bfe298341.png)

2. App accepts spaces without characters. May, it would be better if the app showed an empty message?

![image](https://user-images.githubusercontent.com/74463827/179970940-11dc203a-d461-4d11-a1b2-4feefb931141.png)
3. Using the dashboard I found the Postgres image and pressed the pull button. During pulling progress I moved to the containers/images page, but there is nothing. And I checked using docker if images/containers really exist. And it was an error of the app. No problem docker. Then tried to refresh the page, and got an error. 
![image](https://user-images.githubusercontent.com/74463827/179972237-a1f6ca12-d5cb-4faa-ab72-1589709fa949.png)
Looks like, the error is in API. I've requested images during pulling progress and API still not responding now. 
![image](https://user-images.githubusercontent.com/74463827/179972637-4c4f604f-8ada-443c-a3f0-a86413180b18.png)
It responded when pulling finished.
![image](https://user-images.githubusercontent.com/74463827/179973516-d4ad3d27-ec3d-4002-a824-0ebb151adc5e.png)
But, After this, I realized that there is no problem with docker lib. Maybe the problem is with async or web framework, I don't know. But fixing this issue will be good.

**Comment by AbduazizZiyodov** [comment]
> ![image](https://user-images.githubusercontent.com/74463827/179969085-5de95739-52c4-4817-bd6f-a4f1ccaf0dc9.png)
> 
> Look at the image. I've entered an invalid name. App showed a message that this is an invalid name. But after it, App continued showing the Running... message for valid names.
> 
> If user enters invalid name: show(InvalidMessage()) dont_show(RunningMessage())
> 
> Or is this behavior is project feature if I've mistaken?

Some images take a long (k8s ...) time to run. It would be best if you look at this line of [code](https://github.com/AbduazizZiyodov/docker-dashboard/blob/aa04538db81b54618416413b587a325fd2a0cf61/src/client/src/app/components/modal/run-container-modal/run-container-modal.component.ts#L38). Messages like this, inform you about the "something is started" (neither failed nor succeeded) and will be shown first.

**Comment by AxadjonovOyatillo21** [comment]
> > ![image](https://user-images.githubusercontent.com/74463827/179969085-5de95739-52c4-4817-bd6f-a4f1ccaf0dc9.png)
> > Look at the image. I've entered an invalid name. App showed a message that this is an invalid name. But after it, App continued showing the Running... message for valid names.
> > If user enters invalid name: show(InvalidMessage()) dont_show(RunningMessage())
> > Or is this behavior is project feature if I've mistaken?
> 
> Some images take a long (k8s ...) time to run. It would be best if you look at this line of [code](https://github.com/AbduazizZiyodov/docker-dashboard/blob/aa04538db81b54618416413b587a325fd2a0cf61/src/client/src/app/components/modal/run-container-modal/run-container-modal.component.ts#L38). Messages like this, inform you about the "something is started" (neither failed nor succeeded) and will be shown first.

But after informing that data was invalid, there is no processes at background. May, it would be better if we change order, for example first we should print Running then result of process.

**Comment by AbduazizZiyodov** [comment]
The ordering is absolutely right. If you used libraries like a `toastr`, you should know that every alert message adds from the **TOP**.

**Comment by AxadjonovOyatillo21** [comment]
> The ordering is absolutely right. If you used libraries like a `toastr`, you should know that every alert message adds from the **TOP**.

Sorry. Thank you !
